apiVersion: v1
kind: Service
metadata:
  name: zwitscher-monitor
  labels:
    zwitscher: monitor
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service. Do not use locally.
  # type: LoadBalancer
  ports:
  - port: 8989
  selector:
    zwitscher: monitor
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zwitscher-monitor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        zwitscher: monitor
    spec:
      containers:
      - name: zwitscher-monitor
        image: "qaware-oss-docker-registry.bintray.io/zwitscher/zwitscher-monitor"
        imagePullPolicy: Always
        ports:
        - containerPort: 8989
        livenessProbe:
          httpGet:
            path: /admin/health
            port: 8989
          initialDelaySeconds: 120
          timeoutSeconds: 5
        env:
        - name: EUREKA_HOST
          value: zwitscher-eureka