zuul:
  ignoredServices: '*'
  routes:
    tweets:
      path: /tweets/**
      serviceId: zwitscher-service
      stripPrefix: false
    config:
      path: /config/**
      serviceId: zwitscher-config
      stripPrefix: true