info:
  component: Zwitscher Monitoring Server

server:
  port: 8989

turbine:
  appConfig: zwitscher-service,zwitscher-board,zwitscher-edge
  instanceUrlSuffix: /admin/hystrix.stream
  instanceInsertPort: true
  aggregator:
    clusterConfig: ZWITSCHER
