info:
  component: Zwitscher Eureka Server

server:
  port: 8761

management:
  context-path: /admin

logging:
  level:
    ROOT: INFO
    com.netflix.discovery: INFO
    org.springframework.cloud: INFO

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false